### ISSUE TITLE
Unknown recognition error on startup

### ISSUE THREAD

**Issue by SimonDMurray** [Eco-Flow/synteny#11]
Hi @chriswyatt1,

I remember us speaking about the error produced by synteny pipeline on startup:
`unknown recognition error type: groovyjarjarantlr4.v4.runtime.LexerNoViableAltException`

and I found a corresponding [GitHub issue](https://github.com/nextflow-io/nextflow/issues/2680) which lead to this [pull request](https://github.com/nextflow-io/nextflow/pull/4180).

Have you seen this? I had a quick look at all of your perl scripts and modules and to see if I could identify anything. I notice alot of `\` prior to `.` and `$` which I assume is due to regex interpolation.

Searching your modules I see `chromo.nf` is the only module with this backslach interpolation. 

I am going to look into this unless you have been down this road before? 

Let me know!

Simon

**Comment by chriswyatt1** [comment]
Not looked into it, hopefully there's a way to remove these \ without breaking the code (maybe this is the old way of doing things?)

**Comment by SimonDMurray** [comment]
Hi Chris,

I have fixed the issue. It was related to a stray `\` in `modules/synteny.nf` line 32: `mv karyotype.pdf ${sample_id}.${sample_id2}\.karyotype.pdf`
