### ISSUE TITLE
Move DockerHub images to EcoFlow user

### ISSUE THREAD

**Issue by SimonDMurray** [Eco-Flow/synteny#14]
Issue is we need to keep DockerFiles and conda ymls in a central place that is relatable back to the pipelines themselves. So I (chris) will add the original build files and push them to the new dockerhub>>

Then we must update the docker containers in the modules,,, and test all containers

**Comment by SimonDMurray** [comment]
Simon rewrote and build docker containers for the ecoflow pipeline

**Comment by chriswyatt1** [comment]
Great!
