### ISSUE TITLE
Alter logic of inversion and translocation counting in Synteny Pipeline

### ISSUE THREAD

**Issue by chriswyatt1** [Eco-Flow/synteny#18]

**Comment by chriswyatt1** [comment]
Currently writing a script to do true counts of syntenic junctions that represent inversions, translocations, indels and duplicated regions.

Need to integrate into the synteny pipeline

**Comment by chriswyatt1** [comment]
We need to now check the unit testing and see if everything is still ok, or we need to add more tests

**Comment by SimonDMurray** [comment]
unit testing has been updated to work with new logic
