### ISSUE TITLE
Working on Myriad 

### ISSUE THREAD

**Issue by lewisrevely** [Eco-Flow/synteny#20]
I would like to use this pipeline in UCL's myriad cluster but I'm struggling to work out how to use the correct flags to bring in the correct config file for this environment.

**Comment by SimonDMurray** [comment]
Hi @lewisrevely,

I have committed a working version of the myriad config to our configs repo. You download it onto myriad with:
`wget https://raw.githubusercontent.com/Eco-Flow/configs/main/UCL-myriad/myriad.config` 

It tesed it and it works with our 3 drosophila speices test dataset so if you use species that are huge difference in size (such as human etc) you may need to up the resource requirement!

I should be good to go however!

Thanks,
Simon

**Comment by chriswyatt1** [comment]
When you run on myriad you need to use the following command:

`nextflow run main.nf -bg -c myriad.config --input input.csv `

You need background (`-bg`) so you don't kill the job if you end the terminal

**Comment by chriswyatt1** [comment]
I keep getting the following error:
`ERROR ~ Unknown method invocation `check_max`

 -- Check '.nextflow.log' file for details`
 
 I guess because this is set in the nextflow.config, and the myriad.config is read first

**Comment by SimonDMurray** [comment]
Hi @chriswyatt1,

How are you using the `myriad.config`? Are you supplying it with the `--custom_config` option?

**Comment by chriswyatt1** [comment]
Just with -c myriad.config
I didn't realise this other way

**Comment by SimonDMurray** [comment]
Hi @chriswyatt1,

You need to use the alternative because `-c` replaces the default config. I will add an explanation in the configs repo readme!

Thanks,
Simon

**Comment by chriswyatt1** [comment]
Great. Thanks Simon!

**Comment by chriswyatt1** [comment]
--custom_config fails as well. It starts running locally, and not online sge

No worries though, lets sort this on Monday. It can wait

**Comment by chriswyatt1** [comment]
This is my failed command: `nextflow run main.nf --custom_config myriad.config  -resume -profile singularity --input input.csv`

**Comment by chriswyatt1** [comment]
`ERROR ~ TraceRecord field 'memory' is not set!

 -- Check '.nextflow.log' file for details`

**Comment by chriswyatt1** [comment]
Ok, I got it to work. It was because I had messed with the config. 
I think the config should include singularity, as that is always needed on myriad. Then you wouldn't need to use the -profile as well

**Comment by SimonDMurray** [comment]
Hi @chriswyatt1 ,

I disagree. These additional configs are designed to work for specific architectures and so are about how processes are executed with resources.

If you start to add profile stuff in there it takes away from the modular plug and play methodology of Nextflow.

In my opinion it is easy to understand how profiles and custom configs interact within the documentation as both are explained.

Furthermore myriad wouldn't only work with singularity, apptainer and others could work aswell so limiting it to singularity reduces functionality.

Simon

**Comment by chriswyatt1** [comment]
Hey @SimonDMurray 

If we document this in the README then I think it could be ok. 

It does differ from how nf-core does it (not that we need to follow that way, but people may expect them like that). e.g. https://github.com/nf-core/configs/blob/master/conf/sanger.config and all the other configs I know fix to singularity automatically (or the resources needed for that HPC, else the user has to work that out if its not documented). 

When I ran the pipeline, I assumed wrongly that this was the case (Lewis too, as that was how configs had worked previously). I think <1% of people would want to use apptainer on myriad, so I thought it would make more sense to have this fixed in the config. 

 I cannot get the config to work on myriad, and it looks like a apptainer issue. Which again makes me think setting the container to singularity may be easier (at least for the majority of users), and cause less issues for the user.

```
nextflow run main.nf -resume -profile singularity --input input.csv --custom_config myriad.config
N E X T F L O W  ~  version 23.10.1
Launching `main.nf` [golden_montalcini] DSL2 - revision: 882f04b3aa
=========================================

nf-synteny (v4.0.0)

-----------------------------------------

Authors:
  - Chris Wyatt <c.wyatt@ucl.ac.uk>
  - Simon Murray <simon.murray@ucl.ac.uk>

-----------------------------------------

Copyright (c) 2022

=========================================
Core Nextflow options
  runName        : golden_montalcini
  containerEngine: singularity
  launchDir      : /lustre/scratch/scratch/ucbtcdr/GOTITS_jcvi/synteny
  workDir        : /lustre/scratch/scratch/ucbtcdr/GOTITS_jcvi/synteny/work
  projectDir     : /lustre/scratch/scratch/ucbtcdr/GOTITS_jcvi/synteny
  userName       : ucbtcdr
  profile        : singularity
  configFiles    : 

Input/output options
  input          : input.csv
  outdir         : results

Generic options
  custom_config  : myriad.config

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
executor >  sge (50)
[-        ] process > DOWNLOAD_NCBI                         -
[d1/7966d3] process > FASTAVALIDATOR (Anoplius_nigerrimus)  [100%] 20 of 20, cached: 3 ✔
[17/54ae8c] process > SEQKIT_STATS (Euodynerus_foraminatus) [100%] 20 of 20, cached: 7, failed: 2 ✘
[30/e18625] process > LONGEST (Eumenes_coarctatus)          [ 80%] 16 of 20, cached: 1, failed: 11
[86/a54603] process > GFFREAD (Polistes_dominula)           [100%] 1 of 1
[-        ] process > JCVI                                  -
[-        ] process > SYNTENY                               -
[-        ] process > CHROMOPAINT                           -
[-        ] process > SCORE                                 -
[-        ] process > SCORE_PLOTS                           -
[-        ] process > CUSTOM_DUMPSOFTWAREVERSIONS           -
ERROR ~ Error executing process > 'SEQKIT_STATS (Vespa_velutina)'

Caused by:
  Process `SEQKIT_STATS (Vespa_velutina)` terminated with an error exit status (255)

Command executed:

  seqkit stats \
      --tabular \
      --all \
      Vespa_velutina-GCA_912470025.1-softmasked.fa.gz > 'Vespa_velutina.tsv'
  
  cat <<-END_VERSIONS > versions.yml
  "SEQKIT_STATS":
      seqkit: $( seqkit version | sed 's/seqkit v//' )
  END_VERSIONS

Command exit status:
  255

Command output:
  (empty)

Command error:
  INFO:    Environment variable SINGULARITYENV_TMP is set, but APPTAINERENV_TMP is preferred
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  [ERRO] stat Vespa_velutina-GCA_912470025.1-softmasked.fa.gz: no such file or directory

Work dir:
  /lustre/scratch/scratch/ucbtcdr/GOTITS_jcvi/synteny/work/cd/a65197a474e8575a0ba8371c986626

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details


```

The cached jobs were where is ran without the sge executor on one of my first runs.

**Comment by SimonDMurray** [comment]
Hi @chriswyatt1 ,

Sure thing. Make a pull request then.

Simon

**Comment by chriswyatt1** [comment]
Thanks, OK, all working, was all an issue on my myriad account. 
As you say, we shouldn't force singularity in the profile, so I think this issue is sorted
