### ISSUE TITLE
Collect versions of every tool used in each module

### ISSUE THREAD

**Issue by SimonDMurray** [Eco-Flow/synteny#25]

**Comment by SimonDMurray** [comment]
I have now added initial versions of registering the versions of each major software in each module, @chriswyatt1 can you check if there is any additional software you want to be added to these version files

**Comment by chriswyatt1** [comment]
Ill do this tomorrow. Then i can try to integrate this with a automated method writing.

**Comment by SimonDMurray** [comment]
Hi Chris,

I already did it, following nf-core standards. If you want to add extra tools or software to the format feel free!

Simon
