### ISSUE TITLE
gffread is producing transcript IDs, and not gene IDs

### ISSUE THREAD

**Issue by chriswyatt1** [Eco-Flow/synteny#30]
Not sure if this is related to the changes in NCBI genome download, but for some species, gffread is prodcuing transcript IDS, when it must run with genes:
1	transcript:ENSBTS**T**00005048183	
1	transcript:ENSBTS**T**00005074599	

Should be something like this with a G: ENSBTS**G**000027854

We need to test why this is happening, and if we can change the code to force it to print one gene per gene region, not all the transcripts. 

It doesn't break the synteny pipeline, but is quite ugly, as there are "duplicated" pairs in synteny,,, which are just isoforms of the same gene

**Comment by chriswyatt1** [comment]
I did have code to fix this previously, its in this commit :

dbe28fb

**Comment by SimonDMurray** [comment]
So you can remove each transcript line with something like:
`awk '$3!~"transcript"' gff_file.gff`

that will then lead to duplicates of the exon rows as theres a set of exon rows per transcript right? 
i.e.:
```
gene1
transcript1
exon1
exon2
transcript2
exon1
exon2
gene2
transcript3
exon3
exon4
transcript4
exon3
exon4
```
you remove all the transcripts so it then looks like:
```
gene1
exon1
exon2
exon1
exon2
gene2
exon3
exon4
exon3
exon4
```
so at that point you would need to remove duplicates with the following:
`awk '$3!~"transcript"' gff_file.gff | awk '!a[$0]++'`

which would result in:
```
gene1
exon1
exon2
gene2
exon3
exon4
```

`awk '$3!~"transcript"'` - means remove every line where third column containers the string "transcript"
`awk '!a[$0]++'` - create an array of each line of the file, if there are duplicates increase the increment value, dont print arrays with an increment value greater than 0 (so no duplicates are printed)

**Comment by chriswyatt1** [comment]
Cool, we should try it. 

I also made a new branch: https://github.com/Eco-Flow/synteny/tree/Test_longest_dev
WHere I brought back an old LONGEST module to find the longest isoform in each genome. Though I can;t get it to work, as I would need to push the container to quay. Maybe you could show me (after the launch)

**Comment by chriswyatt1** [comment]
Fixed, now the biggest isoform of all gene is kept using the agat program in the LONGEST module.
