### ISSUE TITLE
Crazy load

### ISSUE THREAD

**Issue by yannickwurm** [Eco-Flow/synteny#34]
<img width="693" alt="Screenshot 2024-02-22 at 15 03 00" src="https://github.com/Eco-Flow/synteny/assets/150113/7df9c925-eec8-4f77-ae9c-901964afb7ea">

Somewhat related - gitpod seemed to indicate that I was only allowed 4CPUs when it started up.

**Comment by SimonDMurray** [comment]
Hi @yannickwurm,

This is the default that GitPod allows you to have (4 cores, 8GB of RAM). 
If you select the drop down option next to GitPod open button (a downwards pointing arrow) you should see "open with options...". 
This will take you to your Gitpod workspace select a "standard" or "large" workspace. A "large" workspace has 8 cores and 16GB RAM. 
Those are the only free tier options available, if you are interested [here](https://www.gitpod.io/pricing?plan=cloud) is their pricing schematic.

Thanks,
Simon
