### ISSUE TITLE
Add test profiles to Synteny pipeline

### ISSUE THREAD

**Issue by SimonDMurray** [Eco-Flow/synteny#7]
There will be multiple test profiles for scaling:
3 species
5 species 
10 species
50 species
each test csv will be stored in the repo

**Comment by chriswyatt1** [comment]
Hey @SimonDMurray,

Yes, it would be great to have different  "real" test sets of those sizes. AS well as our mini test data for testing the pipeline. 
 
Those seem realistic numbers to test at the same time. I will have to find some species that match those numbers. Not sure if I can find 50 Drosophila genomes of chromosome level quality,,, but maybe.

**Comment by chriswyatt1** [comment]
Added a test_full with drosophila, but all modules tested in pipeline, inc ribbon, go.
Add test_mammal with 8 primate species, these have much larger genomes than drosophila
We could add an even larger dataset in future
